---
name: Continuous Delivery
on:
    push:
        branches: ['release']

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    release:
        name: 'Continuous Delivery - Release'
        runs-on: ubuntu-latest
        environment:
            name: 'Release'
        env:
            NODE_VERSION: 18.17.1
            SITE_URL: https://paulalexserban.github.io/prj--fe-ci-build-system
        steps:
            - name: '📥 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: '🔄  Cache node_modules'
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            # @TODO: should check if any of the sub-projects have changed and only then run the build required

            - name: '🔧 Setup NodeJS ${{ env.NODE_VERSION }}'
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: '📦  Install CI dependencies'
              run: npm install

            - name: '🚀 Create Release'
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
